#!/bin/bash

cd "$(git rev-parse --show-toplevel)"
ESLINT="node_modules/.bin/eslint"
pwd

if [[ ! -x "$ESLINT" ]]; then
  printf "\t\033[30;41mPlease install ESlint\033[0m (yarn add -D eslint)\n"
  exit 1
fi

STAGED_FILES=($(git diff --cached --name-only --diff-filter=ACM | grep ".js$"))

echo "ESLinting ${#STAGED_FILES[@]} files"

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

$ESLINT "${STAGED_FILES[@]}"

ESLINT_EXIT="$?"

if [[ "${ESLINT_EXIT}" == 0 ]]; then
  printf "\n\033[30;42mCOMMIT SUCCESS\033[0m\n"
else
  printf "\n\033[30;41mCOMMIT FAIL:\033[0m Fix ESLint errors and try again :-)\n"
  exit 1
fi

exit $?

